import { Component, useState } from 'react';
import dynamic from 'next/dynamic';
import { useReducedMotion } from 'framer-motion';
import styles from '../../styles/BusinessLab.module.css';
const World=dynamic(()=>import('./BusinessWorld'),{ssr:false});
class SceneBoundary extends Component{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<p>3D unavailable. Use the workflow controls below.</p>:this.props.children;}}
export default function BusinessLab(){
 const [view,setView]=useState(0),[phase,setPhase]=useState(0),[hours,setHours]=useState(3),[day,setDay]=useState('Tuesday'),[service,setService]=useState('Garden cleanup'),[paused,setPaused]=useState(false);const reduced=useReducedMotion();
 const status=['No request yet','Request received','Estimate prepared','Job scheduled','Unsent sample invoice'][phase];
 function reset(){setPhase(0);setView(0);setHours(3);setService('Garden cleanup');setDay('Tuesday');}
 return <section className={styles.lab} aria-labelledby="business-title"><header><div><span>01 / The connected business</span><h2 id="business-title">One request.<br/><em>A whole chain of possibilities.</em></h2></div><p>Run a miniature garden-service business. Start as the customer, switch to the owner, and follow the work through.</p></header>
 <div className={styles.world}><div className={styles.toolbar}><span>SDS / Business in motion</span><button aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'} scene motion</button></div><div className={styles.canvas} aria-hidden="true"><SceneBoundary><World view={view} phase={phase} paused={paused||!!reduced}/></SceneBoundary></div><div className={styles.labels}><span>01 / Customer</span><span>02 / Business</span><span>03 / Schedule</span></div><div className={styles.caption}><strong>0{phase}</strong><p>{status}<small>Fictional business · nothing sent or charged</small></p></div></div>
 <div className={styles.console}><nav aria-label="Demo workspace">{['Customer','Owner','Schedule'].map((v,i)=><button key={v} aria-pressed={view===i} onClick={()=>setView(i)}>0{i+1} / {v} ↗</button>)}</nav><div className={styles.panel}><div><span>Explore the {['customer’s phone','owner’s workspace','next steps'][view]}</span><h3>{['A job starts here.','From inquiry to estimate.','Make room for the work.'][view]}</h3><p>{['Choose a service and create a sample inquiry.','Adjust the scope and prepare an estimate from the request.','Simulate acceptance, scheduling, and an unsent invoice.'][view]}</p></div><div className={styles.fields}>
 {view===0?<><label>Sample service<select value={service} disabled={phase>0} onChange={e=>setService(e.target.value)}>{['Garden cleanup','Hedge trimming','Seasonal planting'].map(s=><option key={s}>{s}</option>)}</select></label><button className={styles.action} onClick={()=>{if(!phase)setPhase(1);setView(1);}}>{phase?'Open owner workspace':'Create sample request'} →</button></>:view===1?phase===0?<button className={styles.action} onClick={()=>setView(0)}>Create a request first →</button>:<><div className={styles.receipt}><small>DEMO–001 / {service}</small><strong>Sample estimate: ${hours*40}</strong><small>Illustrative $40/hour rate. Not SDS pricing.</small></div><label>Sample scope · {hours} hours<input type="range" min="1" max="8" value={hours} disabled={phase>=2} onChange={e=>setHours(Number(e.target.value))}/></label><button className={styles.action} onClick={()=>{if(phase===1)setPhase(2);setView(2);}}>{phase===1?'Prepare estimate':'View prepared estimate'} →</button></>:phase<2?<button className={styles.action} onClick={()=>setView(1)}>Prepare an estimate first →</button>:<><div className={styles.receipt}><small>DEMO–001 / {phase===4?'UNSENT INVOICE':'SAMPLE ESTIMATE'}</small><strong>{service} · ${hours*40}</strong><small>{phase>=3?`${day} · simulated booking`:'Awaiting simulated acceptance'}</small></div><label>Sample day<select value={day} disabled={phase>=3} onChange={e=>setDay(e.target.value)}>{['Tuesday','Wednesday','Friday'].map(d=><option key={d}>{d}</option>)}</select></label><button className={styles.action} onClick={()=>phase===4?reset():setPhase(phase+1)}>{phase===2?'Simulate acceptance':phase===3?'Simulate completion & invoice':'Start again'} →</button></>}
 </div></div></div><footer><p role="status">{status}. {phase>0?`${service} · $${hours*40} illustrative total.`:''}</p><button onClick={reset}>Reset demo ↺</button></footer></section>;
}
